export { SlidesShow } from './SlidesShow'
export { Services } from './Services'
export { Service } from './Service'
export { Navbar } from './Navbar'
export { Header } from './Header'
export { Footer } from './Footer'
export { Customers } from './Customers'
export { ContactForm } from './ContactForm'
export { AccordionItem, Accordion } from './AccordionItem'
export { AboutUs } from './AboutUs'
export { ModalCookies } from './ModalCookies'
